### ISSUE TITLE
How do we run flink-crawler in AWS?

### ISSUE THREAD

**Issue by Schmed** [ScaleUnlimited/flink-crawler#12]
It looks like [AWS has an EMR configuration](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-flink.html) that supports Flink 1.1.3 as a Yarn application (see also this [AWS blog post](https://aws.amazon.com/blogs/big-data/use-apache-flink-on-amazon-emr/)). We need Flink 1.2.0 (for the time-based stuff we're doing). Therefore, we'll have to set up a bootstrap action (or whatever such configuration tweaks are called these days in EMR) to update the Flink version. Another option might be to [just install Flink on an existing EMR cluster](https://ci.apache.org/projects/flink/flink-docs-release-1.0/setup/aws.html#install-flink-on-emr-cluster).

**Comment by Schmed** [comment]
I'm also able to instantiate both of the **shaded** versions of these classes at the beginning of CrawlTool (i.e., org.apache.flink.hadoop.shaded.org.apache.http.impl.conn.DefaultHttpRoutePlanner and org.apache.flink.hadoop.shaded.org.apache.http.conn.ConnectionKeepAliveStrategy), but the AmazonHttpClient constructor still fails:

Exception instantiating AmazonHttpClient: org/apache/http/conn/ConnectionKeepAliveStrategy
java.lang.NoClassDefFoundError: org/apache/http/conn/ConnectionKeepAliveStrategy
	at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:147)
	at com.scaleunlimited.flinkcrawler.tools.CrawlTool.<clinit>(CrawlTool.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:528)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:419)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:381)
	at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:838)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:259)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1086)
	at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1133)
	at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1130)
	at org.apache.flink.runtime.security.HadoopSecurityContext$1.run(HadoopSecurityContext.java:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:40)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1130)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.ConnectionKeepAliveStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
Command exiting with ret '255'

**Comment by Schmed** [comment]
Ken got [Running flink crawler in EMR](https://github.com/ScaleUnlimited/flink-crawler/wiki/Running-flink-crawler-in-EMR) working using Flink 1.4 (see https://github.com/ScaleUnlimited/flink-crawler/pull/82/commits).

**Comment by kkrugler** [comment]
Hi @Schmed - please confirm that my write-up actually works, and then close this.

**Comment by Schmed** [comment]
I tried Ken's write-up and it seemed to work. It doesn't provide much information about the available crawler parameters (e.g., common-crawl mode) or where one might expect to find log files, but I guess we do know how to get the code running in AWS.
